version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npx @commitlint/cli --from=origin/master --to=HEAD --verbose
  tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run semantic-release

workflows:
  test:
    jobs:
      - lint
      - tests
      - publish_to_npm:
          filters:
            branches:
              only: master
          requires:
            - lint
            - tests
